#!/bin/bash -e

#  FROM_S3/<transaction_id> to jsonlds and files

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

transactions_file="${JOBPATH}/api_transactions"

#if no trasactions provided, error and exit
if [ ! -e "$transactions_file" ]; then
    echo "No api_transactions file in job directory"
    exit 1
fi

#get transaction id
trx_id=$(jq --raw-output  .trx_id $transactions_file)

# copy json to JOBPATH base dir
for i in $(ls ${JOBPATH}/FROM_S3/$trx_id/*json)
do
	cp -f $i ${JOBPATH}/$(basename $i)
done

#rename to jsonld
rename .json .jsonld ${JOBPATH}/*json

#copy WEBHOOK created by upload
cp -f ${JOBPATH}/FROM_S3/$trx_id/WEBHOOK ${JOBPATH}/WEBHOOK

#reassemble upload segments, & rename using nd:filename
for i in $(ls ${JOBPATH}/metadata-file*jsonld)
do
    pid=$(jq --raw-output '.["@id"]' $i)
    pid=$(echo $pid | sed "s/und://")
    filename=$(jq --raw-output '.["nd:filename"]' $i)

    cat ${JOBPATH}/FROM_S3/$trx_id/${pid}* > ${JOBPATH}/$filename
done
