#!/bin/bash

# Assign pids to objects in ROF files

scriptdir=$(cd $(dirname $0); pwd)
source $scriptdir/conf

cd $gemfile_dir
for rof_file in $JOBPATH/*.rof; do
	if [ ! -e $rof_file ]; then
		echo "No ROF files in job directory"
		exit 1
	fi

	if bundle exec rof filter label \
			--prefix $noid_prefix \
			--noids $noid_url:$noid_pool \
			$rof_file > $rof_file.new; then
		# it worked. replace original file with temp file
		mv $rof_file.new $rof_file
	else
		# error
		exit 1
	fi
done