#!/bin/bash

# Index the data into solr
#
# We rely on the application to do this. So we just send the paths
# to the application (which then adds jobs to the background queue)

scriptdir=$(cd $(dirname $0); pwd)
source $scriptdir/conf

cd $gemfile_dir
for f in "$JOBPATH"/*.rof; do
    if [ ! -e $f ]; then
        echo "No ROF files in job directory"
        exit 1
    fi

    temp_file=$f.id

    if ! cat $f | jq --raw-output '.[]|select(.type == "fobject"and ."af-model" == "GenericFile")|.pid' > $temp_file; then
        echo "Problem parsing $f"
        exit 1
    fi

    if ! su app -c "REDIS_HOST_PORT=$redis_host_port bundle exec tasks/add-to-queue.rb < $temp_file; then
        echo "Problem contacting the redis server"
        exit 1
    fi

    rm $temp_file
done
