#!/bin/bash -e

# Use ROF compare to compare fedora and bendo rof files

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

pid_file="${JOBPATH}/fedora-pids"

cd "$gemfile_dir"

#if no pids provided, error and exit
if [ ! -e "$pid_file" ]; then
    echo "No fedora-pids file in job directory"
    exit 1
fi

# Iterate through pids- use rof compare to compare
# Delete rof if identical to tape
for pid  in $(jq --raw-output 'keys|.[]' < $pid_file ); do

  this_pid=$( echo $pid | sed 's/und://')
  this_bendo=$(jq --raw-output '.[]["bendo-item"]' "${JOBPATH}/${this_pid}.rof")

  if ! bundle exec rof compare "${JOBPATH}/${this_pid}.rof" "${JOBPATH}/FROM_TAPE/${this_bendo}/fedora3/${this_pid}.rof"   ; then
    rm -f ${JOBPATH}/${this_pid}.rof
  fi
done

# get rid of these if they exist
rm -rf ${JOBPATH}/FROM_TAPE


