#!/bin/bash -e

# Translate CSV files into ROF files

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

cd "$gemfile_dir"
for csv_file in "$JOBPATH"/metadata-*.csv; do
  if [ ! -e "$csv_file" ]; then
    echo "No metadata-* CSV files in job directory"
    exit 1
  fi

  rof_file=${csv_file%.csv}.rof
  echo "$csv_file"
  if ! bundle exec csv_to_rof < "$csv_file" > "$rof_file"; then
    exit 1
  fi
done
