#!/bin/bash -e

# Read list of GenericFiles Pids- retrieve from fedora translate into ROF files

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

cd "$gemfile_dir"

pid_file="${JOBPATH}/genericfile-pids"


#if no pids provided, error and exit
if [ ! -e "$pid_file" ]; then
    echo "No genericfiles-pids file in job directory"
    exit 1
fi

# Iterate through pids- use rof fedora_to_rof to retrieve from fedora and generate rof
for pid in $(jq -r 'to_entries[] | [.key, .value] | @csv' ${pid_file}); do
  fedora_id=`echo $pid | sed 's/"//g' | sed 's/und://' | awk 'BEGIN{FS=","}{ print $1}'`
  bendo_id=`echo $pid | sed 's/"//g' | sed 's/und://' | awk 'BEGIN{FS=","}{ print $2}'`

  file_label=$(jq --raw-output '.[]["content-meta"]["label"]' "$JOBPATH/metadata-${fedora_id}.rof")
  unique_file_label="${fedora_id}-${file_label}"

  # if content is in nested directory, create directory
  content_dir=$(dirname $unique_file_label)

  if [ $content_dir != "." ]; then
      mkdir -p "$JOBPATH/$content_dir"
  fi

  download_file="$JOBPATH/$unique_file_label"

  # assume we have already done the download if the file exists
  if [ -e $download_file ]; then
    printf "already downloaded ${unique_file_label}...\n"
  else
    # download content
    curl -k -s -o $download_file  --user ${fedora_user}:${fedora_pass}   ${fedora_url}/objects/und:${fedora_id}/datastreams/content/content?download=true 
  fi

  curl -k -s -o "$JOBPATH/content_ds" --user ${fedora_user}:${fedora_pass}   ${fedora_url}/objects/und:${fedora_id}/datastreams/content?format=xml

  # compute content MD5 checksum

  checksum=$(md5sum $download_file | cut -d' ' -f 1)

  checksum_found=$(grep "$checksum" "$JOBPATH/content_ds" | wc -l) 

  # if MD5 checksum not present in datastream, return error
  # if item has no content datastream, skip it.

  if [ $checksum_found -eq 0 ]; then
     rm -f $download_file
     grep "No datastream could be found" $JOBPATH/content_ds >/dev/null
     if [ $? -eq 0 ]; then
         echo "Warning: Genericfile for ${fedora_id} has no content datastream. removing metadata-${fedora_id}.rof and skipping"
         rm -f "$JOBPATH/metadata-${fedora_id}.rof"
         continue
     fi
     echo "Error: $unique_file_label download checksum did not match fedora object."
     exit 1
  fi
  rm -f $JOBPATH/content_ds
  printf "downloaded ${unique_file_label}...\n"
done
