#!/bin/bash -e

# Read list of Fedora Pids- retrieve from fedora translate into ROF files

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

cd "$gemfile_dir"

pid_file="${JOBPATH}/fedora-pids"

#if no pids provided, error and exit
if [ ! -e "$pid_file" ]; then
    echo "No fedora-pids file in job directory"
    exit 1
fi

# Iterate through pids- use rof fedor_to_rof to retrieve from fedora and generate rof
for pid in $(jq --raw-output 'keys|.[]' $pid_file); do

  noid=$(echo $pid | sed 's/und://')

  if ! bundle exec fedora_to_rof --fedora ${fedora_url} --user "${fedora_user}:${fedora_pass}" --outfile "$JOBPATH/${noid}.rof" $pid; then
    exit 1
  fi
done
