#!/bin/bash

# convert any uri-unsafe filenames in URL or label
# subelements of content-meta field to usable ones.

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

cd "$gemfile_dir"
for rof_file in "$JOBPATH"/metadata-*.rof; do
  if [ ! -e "$rof_file" ]; then
    echo "No ROF files in job directory"
    exit 1
  fi

  echo "$rof_file"
  if bundle exec rof filter filename-normalize "$rof_file" > "$rof_file.filenorm" 2> "$rof_file.err"; then
    err_file_length=$(cat "$rof_file.err" | wc -c)
    # no errors- it worked. replace original file with temp file
    if [ $err_file_length == 0 ] ; then
    	mv "$rof_file.filenorm" "$rof_file"
    else
	# rof filter had errors"
	exit 1
    fi
  else
    # error. don't remove the temporary rof file in case it is important.
    # it will be overwritten next time, anyway
    exit 1
  fi
done
