#!/bin/bash -e

# Read hash of OSF project/registration  URLS--> retrieve from OSF

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

osf_projects="${JOBPATH}/osf_projects"

#if no pids provided, error and exit
if [ ! -e "$osf_projects" ]; then
  echo "No OSF registration file in job directory"
  exit 1
fi

#Create FROM_OSF dir if needed
if [ ! -e "${JOBPATH}/FROM_OSF" ]; then
  mkdir -p "${JOBPATH}/FROM_OSF" 
fi

# Iterate through urls
for this_project  in $(jq --raw-output .project_identifier < $osf_projects ); do

  package_name=${this_project}
  package_url="https://api.osf.io/v2/registrations/${package_name}/"


  java -jar /opt/batchs/scripts/osf-cli.jar -c /opt/batchs/tasks/osf-cli.conf -n $package_name -o ${JOBPATH}/FROM_OSF $package_url

  #if download fails, error and exit
  if [ $? -ne 0 ]; then
    echo "OSF-CLI returns $?"
    exit 1
  fi
done
