#!/bin/bash -e

# Read hash of Fedora Pids--> bendo ids retrieve ROF from Bendo

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

pid_file="${JOBPATH}/fedora-pids"

#if no pids provided, error and exit
if [ ! -e "$pid_file" ]; then
    echo "No fedora-pids file in job directory"
    exit 1
fi
#if no pids provided, error and exit
if [ ! -e "${JOBPATH}/FROM_TAPE" ]; then
	mkdir -p "${JOBPATH}/FROM_TAPE" 
fi

# Iterate through pids- use rof blicleint to retrieve from bendo and bendo rof under FROM_TAPE
for pid  in $(jq 'keys' < $pid_file | jq --raw-output '.[]'); do

  this_pid=$( echo $pid | sed 's/und://')
  this_bendo=$(jq --raw-output '.[]["bendo-item"]' "${JOBPATH}/${this_pid}.rof")

  if ! /opt/batchs/bin/bclient -root "${JOBPATH}/FROM_TAPE" -token $bclient_api_key -server $bendo_url  get $this_bendo "fedora3/${this_pid}.rof"  ; then
    rm -rf "${JOBPATH}/FROM_TAPE"
    exit 1
  fi
done
