#!/bin/bash -e

# Read hash of Fedora Pids--> bendo ids retrieve ROF from Bendo

scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

pid_file="${JOBPATH}/fedora-pids"

#if no pids provided, error and exit
if [ ! -e "$pid_file" ]; then
    echo "No fedora-pids file in job directory"
    exit 1
fi

mkdir -p "${JOBPATH}/FROM_TAPE"

# Iterate through pids
# look for a file ${noid}.rof, use that to get bendo path and then download the
# bendo version of this pid's rof file into the TO_TAPE directory.
for pid in $(jq --raw-output 'keys|.[]' "$pid_file"); do
    noid=$(echo $pid | sed 's/und://')
    this_bendo=$(jq --raw-output '.[]["bendo-item"]' "${JOBPATH}/${noid}.rof")
    target="${JOBPATH}/FROM_TAPE/${this_bendo}/fedora3/${noid}.rof"

    # if target file already exists, assume it has already been downloaded
    if [ -e "$target" ]; then
        continue
    fi

    if ! bclient -root "${JOBPATH}/FROM_TAPE" -token "$bclient_api_key" -server "$bendo_url" get $this_bendo "fedora3/${noid}.rof" ; then
        exit 1
    fi

    # for comparison's sake, add bendo_url to bendo rof files
    sed -i "s|bendo:|${bendo_url}|g" "${target}"
done
