#!/bin/bash

# Ingest data into fedora

scriptdir=$(cd $(dirname $0); pwd)
source $scriptdir/conf

cd $gemfile_dir
exec su app -c "bundle exec rof ingest --fedora $fedora_url --user $fedora_user:$fedora_pass --path '$JOBPATH' '$JOBPATH'/*.rof"
