#!/bin/bash

# Rearrange files to prepare for bendo ingest.
# this file exists to springboard into arrange-files.rb
# (Why? because we need to use bundler to get a newer ruby)

scriptdir=$(cd $(dirname $0); pwd)
source $scriptdir/conf

export JOBPATH

cd $gemfile_dir
for f in "$JOBPATH"/metadata-*.rof; do
    if [ ! -e $f ]; then
        echo "No ROF files in job directory"
        exit 1
    fi

    if bundle exec tasks/arrange-files.rb "$f"; then
        true
    else
        echo "error with $f"
        exit 1
    fi
done
