#!/bin/bash

#set up batch job environment
scriptdir=$(cd $(dirname $0); pwd)
source $scriptdir/conf
export JOBPATH

meta_rof=$(ls metadata*rof)

for meta_rof in "SJOBPATH/metada-*.rof"
do
  # for each image file
  for img_pid in $(jq --raw-output '.[]|select(."af-model" == "GenericFile")|.pid' $meta_rof )
  do
  	# if file has nd:iiif-sequence-order set, add in to manifest
  	image_filename=$(jq --arg IMG_PID $img_pid --raw-output '.[]|select(.pid == $IMG_PID)|.["content-meta"]["label"]' $meta_rof)	
  	parent_pid=$(jq --arg IMG_PID $img_pid --raw-output '.[]|select(.pid == $IMG_PID)|.["rels-ext"]["isPartOf"][0]' $meta_rof)
  	sequence_num=$(jq --arg IMG_PID $img_pid --raw-output '.[]|select(.pid == $IMG_PID)|.["metadata"]["nd:iiif-sequence_order"]' $meta_rof)
  	unique_identifier=$parent_pid
  	label=$(jq --arg PID $parent_pid --raw-output '.[]|select(.pid == $PID)|.["metadata"]["dc:title"]' $meta_rof)
  	description=$(jq --arg PID $parent_pid --raw-output '.[]|select(.pid == $PID)|.["metadata"]["dc:abstract"]' $meta_rof)
  	license=$(jq --arg PID $parent_pid --raw-output '.[]|select(.pid == $PID)|.["metadata"]["dc:rights#permissions"]' $meta_rof)
	attribution=$(jq --arg PID $parent_pid --raw-output '.[]|select(.pid == $PID)|.["metadata"]["dc:creator#administrative_unit"]' $meta_rof)

	mkdir -p TO_IIIF/${unique_identifier}  
	mkdir -p TO_IIIF/${unique_identifier}/images  

	#we'll need to sort these and add the header line when we're done
	if [ ! -f TO_IIIF/${unique_identifier}/sequence.csv ]; then
		printf "Filenames,Label,Description\n" > TO_IIIF/${unique_identifier}/sequence.csv
	fi

	cp $image_filename TO_IIIF/${unique_identifier}/images 
	printf "%s,%s,'%s'\n" ${image_filename} ${sequence_num} "${description}" >> TO_IIIF/${unique_identifier}/sequence.csv

	printf "'%s','%s','%s',%s,,Sequence1,individuals,%s,msuhovec@nd.edu\n" "${label}" "${description}" "${license}" "${attribution}" "${unique_identifier}" >>  TO_IIIF/${unique_identifier}/main.csv
  done
done

$(printf "Filenames,Label,Description\n" > TO_IIIF/${unique_identifier}/sequence.csv | tail -n 2 TO_IIIF/${unique_identifier}/sequence.csv) > TO_IIIF/${unique_identifier}/sequence.csv
$(printf "Label,Description,License,Attribution,Sequence_filename,Sequence_label,Sequence_viewing_experience,unique_identifier,Notify,Metadata_label,Metadata_value\n" | tail -n 2 TO_IIIF/${unique_identifier}/main.csv) > TO_IIIF/${unique_identifier}/main.csv
