#!/bin/bash

# Default workflow task
# It adds the actual work to do to the job's task list

# If there are no rof files in the job directory...
if [ -z $(find "$JOBPATH" -maxdepth 1 -name 'metadata-*.rof' -print -quit) ]; then
  if [ $(find "$JOBPATH" -maxdepth 1 -name '*.jsonld' -print -quit) ]; then
    # no rof, but jsonld present- convert these to rof
    echo 'addtask:jsonld-to-rof' >> $JOBCONTROL
  else
    # no jsonld or rof files, so process any csv files
    echo 'addtask:remove-csv-bom' >> "$JOBCONTROL"
    echo 'addtask:csv-to-rof' >> "$JOBCONTROL"
  fi
fi
echo 'addtask:work-xlat' >> "$JOBCONTROL"
echo 'addtask:assign-pids' >> "$JOBCONTROL"
echo 'addtask:file-to-url' >> "$JOBCONTROL"
echo 'addtask:filename-normalize' >> "$JOBCONTROL"
echo 'addtask:access-to-relsext' >> "$JOBCONTROL"
echo 'addtask:date-stamp' >> "$JOBCONTROL"
echo 'addtask:validate' >> "$JOBCONTROL"
echo 'addtask:move-files-for-bendo' >> "$JOBCONTROL"
echo 'addtask:upload-to-bendo' >> "$JOBCONTROL"
echo 'addtask:ingest' >> "$JOBCONTROL"
echo 'addtask:index' >> "$JOBCONTROL"
echo 'addtask:characterize' >> "$JOBCONTROL"
echo 'addtask:rof-to-csv' >> "$JOBCONTROL"
