#!/bin/bash

# Default workflow task
# It adds the actual work to do to the job's task list

# relies on globs being expanded in double quotes but not single quotes
# we do not expect too many rof files. If that should not be the case, use find.
if [ "$JOBPATH/metadata-*.rof" = "$JOBPATH"'/metadata-*.rof' ]; then
    # no rof files, so process any csv files
    echo 'addtask:csv-to-rof' >> $JOBCONTROL
    echo 'addtask:assign-pids' >> $JOBCONTROL
fi
echo 'addtask:validate' >> $JOBCONTROL
echo 'addtask:ingest' >> $JOBCONTROL
echo 'addtask:index' >> $JOBCONTROL
echo 'addtask:characterize' >> $JOBCONTROL
