#!/bin/bash

# fedor--only workflow task
# It adds the actual work to do to the job's task list

echo 'addtask:do-fedora-only-works' >> "$JOBCONTROL"
echo 'addtask:do-fedora-only-generic-files' >> "$JOBCONTROL"
echo 'addtask:remove-blacklisted-rofs' >> "$JOBCONTROL"
echo 'addtask:do-fedora-only-content' >> "$JOBCONTROL"
echo 'addtask:filename-normalize' >> "$JOBCONTROL"
echo 'addtask:file-to-url' >> "$JOBCONTROL"
echo 'addtask:access-to-relsext' >> "$JOBCONTROL"
echo 'addtask:date-stamp' >> "$JOBCONTROL"
echo 'addtask:validate' >> "$JOBCONTROL"
echo 'addtask:move-files-for-bendo' >> "$JOBCONTROL"
echo 'addtask:upload-to-bendo' >> "$JOBCONTROL"
echo 'addtask:ingest' >> "$JOBCONTROL"
echo 'addtask:index' >> "$JOBCONTROL"
echo 'addtask:characterize' >> "$JOBCONTROL"
