#!/bin/bash

# start-osf-archive-ingest workflow 
# It adds the actual work to do to the job's task list

echo 'addtask:get-from-osf' >> "$JOBCONTROL"
echo 'addtask:work-xlat' >> "$JOBCONTROL"
echo 'addtask:osf-to-rof' >> "$JOBCONTROL"
echo 'addtask:assign-pids' >> "$JOBCONTROL"
echo 'addtask:file-to-url' >> "$JOBCONTROL"
echo 'addtask:date-stamp' >> "$JOBCONTROL"
echo 'addtask:validate' >> "$JOBCONTROL"
echo 'addtask:move-files-for-bendo' >> "$JOBCONTROL"
echo 'addtask:upload-to-bendo' >> "$JOBCONTROL"
echo 'addtask:ingest' >> "$JOBCONTROL"
echo 'addtask:index' >> "$JOBCONTROL"
echo 'addtask:characterize' >> "$JOBCONTROL"
