#!/bin/bash

# Iterate thru the subdirectories under $JOBPATH/TO_TAPE.
# Each is a bendo item to upload
# Use the bclient tool to upload each item

#upload configuration
scriptdir=$(cd $(dirname $0); pwd)
source $scriptdir/conf

for item in "$JOBPATH"/TO_TAPE/*; do

	echo "ITEM"
	echo $item
	/opt/bendo/gocode/bin/bclient -token $bclient_api_key -server $bendo_url -root $item upload $(basename $item) .

	if [ $? -ne 0 ]; then
	      exit 1
        fi	      
done

exit 0
