#!/bin/bash

# set environment, run upload-to-googledrive.rb script

# upload configuration
scriptdir=$(cd $(dirname $0); pwd)
source "$scriptdir"/conf

export JOBPATH

cd $gemfile_dir

bundle exec /opt/batchs/tasks/upload-to-googledrive.rb
