#!/bin/bash -e

# Validate the ROF data before putting it into fedora

scriptdir=$(cd $(dirname $0); pwd)
source $scriptdir/conf

cd $gemfile_dir
for rof_file in "$JOBPATH"/metadata-*.rof; do
  if [ ! -e $rof_file ]; then
    echo "No ROF files in job directory"
    exit 1
  fi

  echo "$rof_file"
  if ! bundle exec rof validate --path "$JOBPATH" "$rof_file"; then
    exit 1
  fi
done
