development:
  etd_manager_usernames:
  - etd_manager@example.com
  - blakshmi@nd.edu
ci:
  etd_manager_usernames:
  - etd_manager@example.com
test:
  etd_manager_usernames:
  - etd_manager@example.com
production:
  etd_manager_usernames:
  - etd_manager@example.com
