#
# FYI: This file is replaced by a copy for deploys
# to ci, pre_production, and production.
#
development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora
test: &TEST
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
ci:
  <<: *TEST
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://your.production.server:8080/fedora
cucumber:
  <<: *TEST
